spring:
    application:
        name: scbapi-oauth2-client
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header

oauth2Server:
    clientId: "test"
    clientSecret: "test"
    url: "http://localhost:8888/oauth/check_token"
    resourceId: "oauth2-server"

server:
    port: 8082
    error:
        whitelabel:
            enabled: false